package com.vstriutilizer.client;

import net.minecraftforge.api.distmarker.Dist;
import net.minecraftforge.api.distmarker.OnlyIn;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

/**
 * Tracks whether the user has dismissed the integration warning
 */
@OnlyIn(Dist.CLIENT)
public class IntegrationWarningTracker {
    
    private static final Path DISMISS_FILE = Paths.get("config/triutilizer/.integration_warning_dismissed");
    private static boolean dismissed = false;
    private static boolean checked = false;
    
    /**
     * Check if the warning has been dismissed
     */
    public static boolean isDismissed() {
        if (!checked) {
            checked = true;
            dismissed = Files.exists(DISMISS_FILE);
        }
        return dismissed;
    }
    
    /**
     * Set the dismissed state
     */
    public static void setDismissed(boolean dismiss) {
        dismissed = dismiss;
        
        if (dismiss) {
            try {
                // Create parent directory if needed
                Files.createDirectories(DISMISS_FILE.getParent());
                // Create the dismiss file
                Files.writeString(DISMISS_FILE, 
                    "# This file indicates you've dismissed the VS integration warning.\n" +
                    "# Delete this file to see the warning again.\n" +
                    "# Generated by TriutilizerVS\n");
                System.out.println("[VS-Triutilizer] Integration warning dismissed");
            } catch (IOException e) {
                System.err.println("[VS-Triutilizer] Failed to save dismiss state: " + e.getMessage());
            }
        } else {
            try {
                Files.deleteIfExists(DISMISS_FILE);
                System.out.println("[VS-Triutilizer] Integration warning re-enabled");
            } catch (IOException e) {
                System.err.println("[VS-Triutilizer] Failed to delete dismiss file: " + e.getMessage());
            }
        }
    }
    
    /**
     * Reset the tracker (for testing)
     */
    public static void reset() {
        checked = false;
        dismissed = false;
    }
}
